import Providers from '@/providers/providers';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import NextTopLoader from 'nextjs-toploader';
import { NuqsAdapter } from 'nuqs/adapters/react';
import '../styles/globals.css';

// import {  Open_Sans } from "next/font/google";

// const openSans = Open_Sans({
//   variable: "--font-en",
//   subsets: ["latin"],
// });
const openSans = localFont({
  src: '../styles/fonts/open-sans/OpenSans-Variable.ttf',
  variable: '--font-en',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} antialiased`}>
        <NextTopLoader showSpinner={false} />
        <NuqsAdapter>
          <Providers>{children}</Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
